const express= require('express');
const cors =require('cors');
const app=express();
const router=require('./routes/userRoute');
app.set('view engine', 'ejs');
app.use(express.json());
app.use(cors());
app.use(express.urlencoded({ extended: true })); 
app.listen(8080);
app.use(router);